"""Runtime architecture dispatcher for kda_kernels.diffusion.norm_infer.

Auto-generated by scripts/export_kda_kernels/export.py. The SGLang
baseline functions and promoted arch-specific wrappers are imported
before kda_kernels.install() swaps SGLang symbols, keeping fallback
paths non-recursive.
"""

from __future__ import annotations

import importlib
import os
import sys
import warnings
from pathlib import Path
from typing import Any

try:
    import torch
except Exception:  # pragma: no cover - torch is always present in runtime envs
    torch = None

try:
    from sglang.jit_kernel.diffusion.triton.norm import norm_infer as _BASELINE_norm_infer
except Exception:  # pragma: no cover - local export/verify may not have sglang
    _BASELINE_norm_infer = None
try:
    from sglang.jit_kernel.diffusion.triton.rmsnorm_onepass import triton_one_pass_rms_norm as _BASELINE_triton_one_pass_rms_norm
except Exception:  # pragma: no cover - local export/verify may not have sglang
    _BASELINE_triton_one_pass_rms_norm = None

_ARCH_BY_CAPABILITY = {(10, 0): 'b200', (9, 0): 'h200'}
_SUPPORTED_ARCHES = ('h200',)
_IMPL_MODULES = {'norm_infer': {'h200': 'kda_kernels.diffusion.norm_infer._impls.h200.wrapper'}, 'triton_one_pass_rms_norm': {'h200': 'kda_kernels.diffusion.norm_infer._impls.h200.wrapper'}}
_IMPL_CACHE: dict[tuple[str, str], Any] = {}
_IMPL_IMPORT_ERRORS: dict[tuple[str, str], BaseException] = {}
_WARNED_IMPORT_ERRORS: set[tuple[str, str]] = set()

def _impl_dir(arch: str) -> Path:
    return Path(__file__).resolve().parent / '_impls' / arch

def _load_impl(arch: str, module_name: str) -> Any:
    key = (arch, module_name)
    if key in _IMPL_CACHE:
        return _IMPL_CACHE[key]
    path = str(_impl_dir(arch))
    if path not in sys.path:
        sys.path.insert(0, path)
    module = importlib.import_module(module_name)
    _IMPL_CACHE[key] = module
    return module

def _preload_kda_impls(strict: bool = False) -> None:
    """Import promoted wrappers before monkey-patching SGLang."""
    for by_arch in _IMPL_MODULES.values():
        for arch, module_name in by_arch.items():
            key = (arch, module_name)
            if key in _IMPL_CACHE or key in _IMPL_IMPORT_ERRORS:
                continue
            try:
                _load_impl(arch, module_name)
            except Exception as exc:  # noqa: BLE001
                _IMPL_IMPORT_ERRORS[key] = exc
                if strict:
                    raise
                warnings.warn(
                    f'kda_kernels failed to preload {module_name} for {arch}: {exc!r}'
                )

def _iter_tensors(value: Any):
    if torch is not None and isinstance(value, torch.Tensor):
        yield value
    elif isinstance(value, (tuple, list)):
        for item in value:
            yield from _iter_tensors(item)
    elif isinstance(value, dict):
        for item in value.values():
            yield from _iter_tensors(item)

def _select_arch(args: tuple[Any, ...], kwargs: dict[str, Any]) -> str | None:
    forced = os.environ.get('KDA_FORCE_ARCH')
    if forced in _SUPPORTED_ARCHES:
        return forced
    if torch is None:
        return None
    for tensor in _iter_tensors(args):
        if getattr(tensor, 'is_cuda', False):
            try:
                return _ARCH_BY_CAPABILITY.get(tuple(torch.cuda.get_device_capability(tensor.device)))
            except Exception:
                return None
    for tensor in _iter_tensors(kwargs):
        if getattr(tensor, 'is_cuda', False):
            try:
                return _ARCH_BY_CAPABILITY.get(tuple(torch.cuda.get_device_capability(tensor.device)))
            except Exception:
                return None
    return None

def _baseline_or_raise(fn_name: str, baseline: Any, args: tuple[Any, ...], kwargs: dict[str, Any]) -> Any:
    if baseline is None:
        raise RuntimeError(f'No SGLang baseline available for {fn_name}')
    return baseline(*args, **kwargs)

def _call(fn_name: str, baseline: Any, args: tuple[Any, ...], kwargs: dict[str, Any]) -> Any:
    arch = _select_arch(args, kwargs)
    module_name = _IMPL_MODULES.get(fn_name, {}).get(arch)
    if module_name is None:
        return _baseline_or_raise(fn_name, baseline, args, kwargs)
    key = (arch, module_name)
    if key in _IMPL_IMPORT_ERRORS:
        if key not in _WARNED_IMPORT_ERRORS:
            _WARNED_IMPORT_ERRORS.add(key)
            warnings.warn(
                f'kda_kernels falling back for {fn_name}: {module_name} '
                f'failed to preload for {arch}: {_IMPL_IMPORT_ERRORS[key]!r}'
            )
        return _baseline_or_raise(fn_name, baseline, args, kwargs)
    module = _IMPL_CACHE.get(key)
    if module is None:
        # Direct kda_kernels use without install(); safe because SGLang has not
        # been monkey-patched yet in that usage pattern.
        try:
            module = _load_impl(arch, module_name)
        except Exception as exc:  # noqa: BLE001
            _IMPL_IMPORT_ERRORS[key] = exc
            warnings.warn(f'kda_kernels falling back for {fn_name}: {exc!r}')
            return _baseline_or_raise(fn_name, baseline, args, kwargs)
    return getattr(module, fn_name)(*args, **kwargs)

def norm_infer(*args: Any, **kwargs: Any) -> Any:
    return _call('norm_infer', _BASELINE_norm_infer, args, kwargs)

def triton_one_pass_rms_norm(*args: Any, **kwargs: Any) -> Any:
    return _call('triton_one_pass_rms_norm', _BASELINE_triton_one_pass_rms_norm, args, kwargs)

