"""Print the shape table of every task from its bench/workloads*.json.

    python tools/dump_shapes.py            # all tasks, markdown
    python tools/dump_shapes.py <task>     # one task

Same-named tensor across the kept rows is collapsed into one template; a dimension
that varies is replaced by a letter and its observed values are listed, so a reader
sees the shape family instead of N nearly identical rows.
"""
import glob, json, os, sys

LETTERS = "TNMKPQ"


def template(rows, name):
    shapes = [r["args"][name]["shape"] for r in rows
              if isinstance(r["args"].get(name), dict) and "shape" in r["args"][name]]
    if not shapes:
        return None
    nd = len(shapes[0])
    if any(len(s) != nd for s in shapes):
        return "`%s` %s" % (name, sorted({str(s) for s in shapes})[:4])
    parts, varying = [], {}
    for i in range(nd):
        vals = sorted({s[i] for s in shapes})
        if len(vals) == 1:
            parts.append(str(vals[0]))
        else:
            letter = LETTERS[len(varying) % len(LETTERS)]
            parts.append(letter)
            varying[letter] = vals
    info = next(r["args"][name] for r in rows if isinstance(r["args"].get(name), dict))
    nc = any(isinstance(r["args"].get(name), dict) and not r["args"][name].get("contiguous", True)
             for r in rows)
    out = "`%s[%s]` %s%s" % (name, ", ".join(parts), info["dtype"],
                             " **non-contiguous**" if nc else "")
    for k, v in varying.items():
        shown = ", ".join(str(x) for x in v[:10]) + (", ..." if len(v) > 10 else "")
        out += " — %s ∈ {%s}" % (k, shown)
    return out


def dump(task, fh):
    files = sorted(glob.glob(os.path.join(task, "bench", "workloads*.json")))
    if not files:
        return
    print("\n## `%s`\n" % task, file=fh)
    for wf in files:
        d = json.load(open(wf))
        if len(files) > 1:
            print("### %s — model `%s`\n" % (os.path.basename(wf), d.get("model")), file=fh)
        for o in d["ops"]:
            print("**`%s`** — %s real calls, %s distinct signatures, %d rows kept\n"
                  % (o["op"], format(o["total_real_calls"], ","),
                     format(o["distinct_real_signatures"], ","), len(o["rows"])), file=fh)
            names = []
            for r in o["rows"]:
                for k, v in r["args"].items():
                    if isinstance(v, dict) and "shape" in v and k not in names:
                        names.append(k)
            for n in names:
                t = template(o["rows"], n)
                if t:
                    print("- " + t, file=fh)
            print(file=fh)


def main():
    tasks = sys.argv[1:] or sorted(
        d for d in os.listdir(".") if os.path.isdir(d) and d not in ("docs", "tools", ".git"))
    fh = sys.stdout
    print("# Shape tables\n", file=fh)
    print("Generated by `tools/dump_shapes.py` from each task's `bench/workloads*.json`.\n"
          "Call counts are real traffic only (warmup excluded). Regenerate after any\n"
          "recapture rather than editing this file.\n", file=fh)
    for t in tasks:
        dump(t, fh)


if __name__ == "__main__":
    main()
