"""Runtime architecture dispatcher for kda_kernels.diffusion.rotary_embedding.

Auto-generated by scripts/export_kda_kernels/export.py. The SGLang
baseline functions and promoted arch-specific wrappers are imported
before kda_kernels.install() swaps SGLang symbols, keeping fallback
paths non-recursive.
"""

from __future__ import annotations

import importlib
import os
import sys
import warnings
from pathlib import Path
from typing import Any

try:
    import torch
except Exception:  # pragma: no cover - torch is always present in runtime envs
    torch = None

try:
    from sglang.jit_kernel.diffusion.triton.rotary import apply_rotary_embedding as _BASELINE_apply_rotary_embedding
except Exception:  # pragma: no cover - local export/verify may not have sglang
    _BASELINE_apply_rotary_embedding = None
try:
    from sglang.jit_kernel.diffusion.triton.ltx2_rotary import apply_ltx2_split_rotary_emb as _BASELINE_apply_ltx2_split_rotary_emb
except Exception:  # pragma: no cover - local export/verify may not have sglang
    _BASELINE_apply_ltx2_split_rotary_emb = None

_ARCH_BY_CAPABILITY = {(10, 0): 'b200', (9, 0): 'h200'}
_SUPPORTED_ARCHES = ('b200', 'h200')
_IMPL_MODULES = {'apply_rotary_embedding': {'b200': 'kda_kernels.diffusion.rotary_embedding._impls.b200.wrapper', 'h200': 'kda_kernels.diffusion.rotary_embedding._impls.h200.wrapper'}, 'apply_ltx2_split_rotary_emb': {'b200': 'kda_kernels.diffusion.rotary_embedding._impls.b200.wrapper', 'h200': 'kda_kernels.diffusion.rotary_embedding._impls.h200.wrapper'}}
_IMPL_CACHE: dict[tuple[str, str], Any] = {}
_IMPL_IMPORT_ERRORS: dict[tuple[str, str], BaseException] = {}
_WARNED_IMPORT_ERRORS: set[tuple[str, str]] = set()
# Resolved-target cache: (fn_name, device_index) -> bound wrapper callable
# (or the _USE_BASELINE sentinel). Filled on the first call per key so the
# steady-state hot path skips capability probing, module import, and attribute
# lookup -- the per-call dispatch tax that otherwise erases small-shape wins.
_USE_BASELINE = object()
_TARGET_CACHE: dict[tuple[str, Any], Any] = {}
# KDA_FORCE_ARCH is a deploy/debug override, read once at import (not per call).
_FORCED_ARCH = os.environ.get('KDA_FORCE_ARCH')
if _FORCED_ARCH not in _SUPPORTED_ARCHES:
    _FORCED_ARCH = None

def _impl_dir(arch: str) -> Path:
    return Path(__file__).resolve().parent / '_impls' / arch

def _load_impl(arch: str, module_name: str) -> Any:
    key = (arch, module_name)
    if key in _IMPL_CACHE:
        return _IMPL_CACHE[key]
    path = str(_impl_dir(arch))
    if path not in sys.path:
        sys.path.insert(0, path)
    module = importlib.import_module(module_name)
    _IMPL_CACHE[key] = module
    return module

def _preload_kda_impls(strict: bool = False) -> None:
    """Import promoted wrappers before monkey-patching SGLang."""
    for by_arch in _IMPL_MODULES.values():
        for arch, module_name in by_arch.items():
            key = (arch, module_name)
            if key in _IMPL_CACHE or key in _IMPL_IMPORT_ERRORS:
                continue
            try:
                _load_impl(arch, module_name)
            except Exception as exc:  # noqa: BLE001
                _IMPL_IMPORT_ERRORS[key] = exc
                if strict:
                    raise
                warnings.warn(
                    f'kda_kernels failed to preload {module_name} for {arch}: {exc!r}'
                )

def _iter_tensors(value: Any):
    if torch is not None and isinstance(value, torch.Tensor):
        yield value
    elif isinstance(value, (tuple, list)):
        for item in value:
            yield from _iter_tensors(item)
    elif isinstance(value, dict):
        for item in value.values():
            yield from _iter_tensors(item)

def _first_cuda_index(args: tuple[Any, ...], kwargs: dict[str, Any]):
    """Device index of the first CUDA tensor in the call (positional args fast
    path, then nested containers, then kwargs), else None."""
    for value in args:
        if type(value) is torch.Tensor:
            if value.is_cuda:
                return value.device.index
        elif isinstance(value, (tuple, list, dict)):
            for tensor in _iter_tensors(value):
                if getattr(tensor, 'is_cuda', False):
                    return tensor.device.index
    for value in kwargs.values():
        if type(value) is torch.Tensor:
            if value.is_cuda:
                return value.device.index
        elif isinstance(value, (tuple, list, dict)):
            for tensor in _iter_tensors(value):
                if getattr(tensor, 'is_cuda', False):
                    return tensor.device.index
    return None

def _resolve_target(fn_name: str, idx) -> Any:
    """Resolve (fn_name, device idx) -> bound wrapper callable, or _USE_BASELINE.

    Runs the full arch-selection / import path once per cache key; the result is
    memoized by the caller so steady-state calls skip all of this work.
    """
    if _FORCED_ARCH is not None:
        arch = _FORCED_ARCH
    elif torch is None or idx is None:
        arch = None
    else:
        try:
            arch = _ARCH_BY_CAPABILITY.get(tuple(torch.cuda.get_device_capability(idx)))
        except Exception:
            arch = None
    module_name = _IMPL_MODULES.get(fn_name, {}).get(arch)
    if module_name is None:
        return _USE_BASELINE
    key = (arch, module_name)
    if key in _IMPL_IMPORT_ERRORS:
        if key not in _WARNED_IMPORT_ERRORS:
            _WARNED_IMPORT_ERRORS.add(key)
            warnings.warn(
                f'kda_kernels falling back for {fn_name}: {module_name} '
                f'failed to preload for {arch}: {_IMPL_IMPORT_ERRORS[key]!r}'
            )
        return _USE_BASELINE
    module = _IMPL_CACHE.get(key)
    if module is None:
        # Direct kda_kernels use without install(); safe because SGLang has not
        # been monkey-patched yet in that usage pattern.
        try:
            module = _load_impl(arch, module_name)
        except Exception as exc:  # noqa: BLE001
            _IMPL_IMPORT_ERRORS[key] = exc
            warnings.warn(f'kda_kernels falling back for {fn_name}: {exc!r}')
            return _USE_BASELINE
    return getattr(module, fn_name)

def apply_rotary_embedding(*args: Any, **kwargs: Any) -> Any:
    idx = _first_cuda_index(args, kwargs)
    ckey = ('apply_rotary_embedding', idx)
    target = _TARGET_CACHE.get(ckey)
    if target is None:
        target = _resolve_target('apply_rotary_embedding', idx)
        _TARGET_CACHE[ckey] = target
    if target is _USE_BASELINE:
        if _BASELINE_apply_rotary_embedding is None:
            raise RuntimeError('No SGLang baseline available for apply_rotary_embedding')
        return _BASELINE_apply_rotary_embedding(*args, **kwargs)
    return target(*args, **kwargs)

def apply_ltx2_split_rotary_emb(*args: Any, **kwargs: Any) -> Any:
    idx = _first_cuda_index(args, kwargs)
    ckey = ('apply_ltx2_split_rotary_emb', idx)
    target = _TARGET_CACHE.get(ckey)
    if target is None:
        target = _resolve_target('apply_ltx2_split_rotary_emb', idx)
        _TARGET_CACHE[ckey] = target
    if target is _USE_BASELINE:
        if _BASELINE_apply_ltx2_split_rotary_emb is None:
            raise RuntimeError('No SGLang baseline available for apply_ltx2_split_rotary_emb')
        return _BASELINE_apply_ltx2_split_rotary_emb(*args, **kwargs)
    return target(*args, **kwargs)

