"""Retired compatibility entry point.

Prompt workload sections are now regenerated by ``distribute_shapes.py`` from
accepted live capture records. Keeping the old patcher would risk reintroducing
stale shape text, so this script exits with a pointer to the supported command.
"""

from __future__ import annotations


def main() -> None:
    raise SystemExit(
        "patch_prompts.py is retired. Use "
        "`python3 scripts/diffusion_shape_capture/distribute_shapes.py "
        "--input <captures.jsonl> --sweep-log <sweep.log>` instead."
    )


if __name__ == "__main__":
    main()
